fos_rest:
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: true
    exception:
        enabled: true
    body_listener:
        enabled: true
