jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
