version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "15432:5432"
    networks:
      - app-network

  app:
    build:
      dockerfile: ./docker/app/Dockerfile
    restart: on-failure
    volumes:
      - .:/var/www/project
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/project/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge