client.controllers:
    resource: ../src/Client/Infrastructure/Controller/
    type: annotation

account.controllers:
    resource: ../src/Account/Infrastructure/Controller/
    type: annotation

transaction.controllers:
    resource: ../src/Transaction/Infrastructure/Controller/
    type: annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /docs
        permanent: true

app.swagger_ui:
    path: /docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
